#!/bin/sh

# Install dependencies

apt-get install git-core automake libtool libpthread-stubs0-dev xserver-xorg-dev x11proto-xinerama-dev libx11-xcb-dev libxcb-glx0-dev libxrender-dev

apt-get build-dep libgl1-mesa-dri libxcb-glx0-dev

# Download Sources
git clone git://anongit.freedesktop.org/git/mesa/mesa
git clone git://anongit.freedesktop.org/git/mesa/vmwgfx
git clone git://anongit.freedesktop.org/git/mesa/drm
git clone git://anongit.freedesktop.org/git/xorg/driver/xf86-video-vmware

# Build DRM
cd drm
./autogen.sh --prefix=/usr --enable-vmwgfx
make
make install
cd ..

# Build Mesa
cd mesa
./autogen.sh --prefix=/usr --with-gallium-drivers=svga --with-dri-drivers= --enable-xa
make
make install
cd ..

# Build xf86-video-vmware
cd xf86-video-vmware
./autogen.sh --prefix=/usr
make
make install
cd ..

# Delete Old Module
rm /lib/modules/`uname -r`/kernel/drivers/gpu/drm/vmwgfx.ko* 

# Install New Module
cd vmwgfx
make
make install
cp 00-vmwgfx.rules /etc/udev/rules.d
depmod -ae

# Load New Module
modprobe vmwgfx

exit
